import { db, reports, eq } from "@opensight/db";
import { notFound } from "next/navigation";
import { ReportViewer } from "./report-viewer";
import type { Metadata } from "next";

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const report = await db.query.reports.findFirst({
    where: eq(reports.slug, slug),
  });

  if (!report) {
    return { title: "Report Not Found — OpenSight" };
  }

  return {
    title: `${report.title} — OpenSight`,
    description: report.summary ?? "AI Visibility Report generated by OpenSight",
  };
}

export default async function ReportPage({ params }: PageProps) {
  const { slug } = await params;

  const report = await db.query.reports.findFirst({
    where: eq(reports.slug, slug),
  });

  if (!report) {
    notFound();
  }

  if (report.expiresAt && new Date(report.expiresAt) < new Date()) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="text-center space-y-3 max-w-md">
          <div className="w-16 h-16 rounded-2xl bg-amber-100 flex items-center justify-center mx-auto">
            <svg className="w-8 h-8 text-amber-600" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            </svg>
          </div>
          <h1 className="text-xl font-bold text-gray-900">Report Expired</h1>
          <p className="text-gray-500 text-sm">This report link has expired. Please request a new report.</p>
        </div>
      </div>
    );
  }

  if (report.status === "failed") {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="text-center space-y-3 max-w-md">
          <div className="w-16 h-16 rounded-2xl bg-red-100 flex items-center justify-center mx-auto">
            <svg className="w-8 h-8 text-red-600" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z" />
            </svg>
          </div>
          <h1 className="text-xl font-bold text-gray-900">Report Failed</h1>
          <p className="text-gray-500 text-sm">
            {report.errorMessage ?? "Something went wrong while generating this report. Please try again."}
          </p>
        </div>
      </div>
    );
  }

  if (report.status !== "completed") {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="text-center space-y-4 max-w-md">
          <div className="w-16 h-16 rounded-2xl bg-indigo-100 flex items-center justify-center mx-auto">
            <svg className="w-8 h-8 text-indigo-600 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
          </div>
          <h1 className="text-xl font-bold text-gray-900">Generating Your Report...</h1>
          <p className="text-gray-500 text-sm">
            We&apos;re analyzing <span className="font-medium text-gray-900">{report.domain}</span> across AI engines.
            This usually takes 1-2 minutes.
          </p>
          <p className="text-xs text-gray-400">
            We&apos;ll email you when it&apos;s ready. You can also refresh this page.
          </p>
        </div>
      </div>
    );
  }

  return <ReportViewer report={JSON.parse(JSON.stringify(report))} />;
}
